<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ProjectType>Local</ProjectType>
    <OutputType>Library</OutputType>
    <OutputPath>..\binaries\</OutputPath>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
	  <Version>3.3.0</Version>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\FarsiLibrary.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FarsiLibrary.Localization\FarsiLibrary.Localization.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Utils\FarsiLibrary.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Solution Items\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
    <Compile Update="BaseClasses\BaseDateControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="BaseClasses\DateEditBase.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FAContainerComboBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FADatePickerStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FADayView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FAMonthViewStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FAMultiView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="BaseClasses\BaseStyledControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FADatePicker.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="BaseClasses\BaseControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="BaseClasses\TextEditBase.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\FAMonthView.cs">
      <SubType>Component</SubType>
    </Compile>
    <EmbeddedResource Include="Controls\FADatePicker.bmp" />
    <EmbeddedResource Include="Controls\FAMonthView.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Controls\DataGridViewFADateTimePickerEditor.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Controls\FADatePickerStrip.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Controls\FAMonthViewStrip.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Controls\FADayView.bmp" />
  </ItemGroup>
</Project>