<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>..\binaries\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\FarsiLibrary.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FarsiLibrary.Localization\FarsiLibrary.Localization.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Utils\FarsiLibrary.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationFramework.Aero" />
    <Reference Include="PresentationFramework.Classic" />
    <Reference Include="PresentationFramework.Luna" />
    <Reference Include="PresentationFramework.Royale" />
  </ItemGroup>
</Project>