<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <OutputPath>..\binaries\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\FarsiLibrary.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Solution Items\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
    <Compile Update="Demo\DemoBase.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\CustomFormattingAndValidating.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DevExpressCalendar.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DevExpressEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DevExpressGridViewEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\ThemeAndFocusStyle.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\MultiViewControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DayViewControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\Events.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\RightToLeft.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\Cultures.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DateConversion.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DateCalculation.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\ConvertNumbersToWord.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Demo\BindingToDataSet.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\BindingToList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\CustomCulturesAndLocalizer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DateValidation.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DataGridViewColumnEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\UsingThemeManager.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\ToolStripIntegration.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\ToStringFormatter.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\ScrollingOptions.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\Casting.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DayCustomDrawing.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\MessageBoxDisplay.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\MultiSelection.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Pages\DateTimeFormat.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <EmbeddedResource Include="Properties\licenses.licx" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\PersonnelDataSet.xsc">
      <DependentUpon>PersonnelDataSet.xsd</DependentUpon>
    </None>
    <None Update="Data\PersonnelDataSet.xsd">
      <SubType>Designer</SubType>
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>PersonnelDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="Data\PersonnelDataSet.xss">
      <DependentUpon>PersonnelDataSet.xsd</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DevExpress.Drawing.v25.1, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
    <Reference Include="DevExpress.Printing.v25.1.Core, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
    <Reference Include="DevExpress.Data.v25.1, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
    <Reference Include="DevExpress.Data.Desktop.v25.1, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
    <Reference Include="DevExpress.Utils.v25.1, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
    <Reference Include="DevExpress.XtraEditors.v25.1, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
    <Reference Include="DevExpress.XtraGrid.v25.1, Version=25.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FarsiLibrary.Localization\FarsiLibrary.Localization.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Utils\FarsiLibrary.Utils.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Win.DevExpress.16.1\FarsiLibrary.Win.DevExpress.16.1.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Win\FarsiLibrary.Win.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>