<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>FarsiLibrary.WPFDemo.Program</StartupObject>
    <OutputPath>..\binaries\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\FarsiLibrary.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Solution Items\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FarsiLibrary.Localization\FarsiLibrary.Localization.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Utils\FarsiLibrary.Utils.csproj" />
    <ProjectReference Include="..\FarsiLibrary.Win\FarsiLibrary.Win.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\App.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationFramework.Aero" />
    <Reference Include="PresentationFramework.Classic" />
    <Reference Include="PresentationFramework.Luna" />
    <Reference Include="PresentationFramework.Royale" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Logo.png" />
  </ItemGroup>
</Project>